"""
拉丁学名补充 v3 - 覆盖剩余298条
运行：python src/database/enrich_latin_names_v3.py
"""
import sqlite3, os

DB_PATH = os.environ.get("DB_PATH", "data/tcm_exosome.db")
SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")

LATIN_MAP = {
    "千金子霜": "Euphorbia lathyris L.",
    "大蓟炭": "Cirsium japonicum Fisch. ex DC.",
    "大血藤": "Sargentodoxa cuneata (Oliv.) Rehd. et Wils.",
    "大豆黄卷": "Glycine max (L.) Merr.",
    "大青盐": "Halitum",
    "天仙子": "Hyoscyamus niger L.",
    "天山雪莲": "Saussurea involucrata (Kar. et Kir.) Sch.-Bip.",
    "天然冰片": "Dryobalanops aromatica Gaertn.f.",
    "天竺黄": "Bambusa textilis McClure",
    "天葵子": "Semiaquilegia adoxoides (DC.) Makino",
    "委陵菜": "Potentilla chinensis Ser.",
    "姜半夏": "Pinellia ternata (Thunb.) Breit.",
    "娑罗子": "Aesculus chinensis Bge.",
    "密蒙花": "Buddleja officinalis Maxim.",
    "小叶莲": "Sinopodophyllum hexandrum (Royle) Ying",
    "小通草": "Stachyurus chinensis Franch.",
    "小驳骨": "Gendarussa vulgaris Nees",
    "山柰": "Kaempferia galanga L.",
    "山楂叶": "Crataegus pinnatifida Bge.",
    "山银花": "Lonicera hypoglauca Miq.",
    "山香圆叶": "Turpinia arguta (Lindl.) Seem.",
    "山麦冬": "Liriope spicata (Thunb.) Lour.",
    "岩白菜": "Bergenia purpurascens (Hook.f. et Thoms.) Engl.",
    "川射干": "Iris tectorum Maxim.",
    "川木香": "Dolomiaea souliei (Franch.) Shih",
    "巫山淫羊藿": "Epimedium wushanense T.S.Ying",
    "巴戟天": "Morinda officinalis How",
    "布渣叶": "Microcos paniculata L.",
    "常山": "Dichroa febrifuga Lour.",
    "干漆": "Toxicodendron vernicifluum (Stokes) F.A.Barkley",
    "平贝母": "Fritillaria ussuriensis Maxim.",
    "广东紫珠": "Callicarpa kwangtungensis Chun",
    "广枣": "Choerospondias axillaris (Roxb.) Burtt et Hill",
    "广金钱草": "Desmodium styracifolium (Osb.) Merr.",
    "当药": "Swertia pseudochinensis Hara",
    "徐长卿": "Cynanchum paniculatum (Bge.) Kitag.",
    "拳参": "Polygonum bistorta L.",
    "救必应": "Ilex rotunda Thunb.",
    "断血流": "Clinopodium chinense (Benth.) O.Ktze.",
    "昆布": "Ecklonia kurome Okam.",
    "明党参": "Changium smyrnioides Wolff",
    "暴马子皮": "Syringa reticulata (Blume) H.Hara",
    "月季花": "Rosa chinensis Jacq.",
    "木棉花": "Gossampinus malabarica (DC.) Merr.",
    "木芙蓉叶": "Hibiscus mutabilis L.",
    "木蝴蝶": "Oroxylum indicum (L.) Vent.",
    "木贼": "Equisetum hyemale L.",
    "木鳖子": "Momordica cochinchinensis (Lour.) Spreng.",
    "朱砂根": "Ardisia crenata Sims",
    "杜仲叶": "Eucommia ulmoides Oliv.",
    "杠板归": "Polygonum perfoliatum L.",
    "松花粉": "Pinus massoniana Lamb.",
    "枫香脂": "Liquidambar formosana Hance",
    "枸骨叶": "Ilex cornuta Lindl. ex Paxt.",
    "柏子仁": "Platycladus orientalis (L.) Franco",
    "柿蒂": "Diospyros kaki Thunb.",
    "核桃仁": "Juglans regia L.",
    "桃枝": "Prunus persica (L.) Batsch",
    "桑叶": "Morus alba L.",
    "桑寄生": "Taxillus chinensis (DC.) Danser",
    "桑枝": "Morus alba L.",
    "桑椹": "Morus alba L.",
    "桑白皮": "Morus alba L.",
    "桑螵蛸": "Tenodera sinensis Saussure",
    "梅花": "Prunus mume (Sieb.) Sieb. et Zucc.",
    "棕榈": "Trachycarpus fortunei (Hook.) H.Wendl.",
    "椿皮": "Ailanthus altissima (Mill.) Swingle",
    "楮实子": "Broussonetia papyrifera (L.) Vent.",
    "榧子": "Torreya grandis Fort.",
    "榼藤子": "Entada phaseoloides (L.) Merr.",
    "槲寄生": "Viscum coloratum (Komar.) Nakai",
    "橘核": "Citrus reticulata Blanco",
    "橘红": "Citrus reticulata Blanco",
    "檀香": "Santalum album L.",
    "母丁香": "Syzygium aromaticum (L.) Merr. et Perry",
    "水牛角": "Bubalus bubalis Linnaeus",
    "水红花子": "Polygonum orientale L.",
    "水飞蓟": "Silybum marianum (L.) Gaertn.",
    "沙苑子": "Astragalus complanatus R.Br.",
    "油松节": "Pinus tabuliformis Carr.",
    "法半夏": "Pinellia ternata (Thunb.) Breit.",
    "洋金花": "Datura metel L.",
    "洪连": "Halerpestes cymbalaria (Pursh) Greene",
    "浮萍": "Spirodela polyrrhiza (L.) Schleid.",
    "海藻": "Sargassum fusiforme (Harv.) Setch.",
    "海马": "Hippocampus kelloggi Jordan et Snyder",
    "海龙": "Syngnathus acus Linnaeus",
    "淡竹叶": "Lophatherum gracile Brongn.",
    "淡豆豉": "Glycine max (L.) Merr.",
    "清半夏": "Pinellia ternata (Thunb.) Breit.",
    "湖北贝母": "Fritillaria hupehensis Hsiao et K.C.Hsia",
    "滇鸡血藤": "Millettia dielsiana Harms",
    "滑石粉": "Talcum",
    "满山红": "Rhododendron dauricum L.",
    "火麻仁": "Cannabis sativa L.",
    "灯心草": "Juncus effusus L.",
    "灯盏细辛": "Erigeron breviscapus (Vant.) Hand.-Mazz.",
    "炉甘石": "Calamina",
    "炒瓜蒌子": "Trichosanthes kirilowii Maxim.",
    "炙甘草": "Glycyrrhiza uralensis Fisch.",
    "炙红芪": "Hedysarum polybotrys Hand.-Mazz.",
    "炙黄芪": "Astragalus membranaceus (Fisch.) Bge.",
    "炮姜": "Zingiber officinale Rosc.",
    "焦栀子": "Gardenia jasminoides Ellis",
    "焦槟榔": "Areca catechu L.",
    "煅石膏": "Gypsum Fibrosum",
    "片姜黄": "Curcuma wenyujin Y.H.Chen et C.Ling",
    "牛黄": "Bos taurus domesticus Gmelin",
    "牡荆叶": "Vitex negundo L.",
    "牵牛子": "Pharbitis nil (L.) Choisy",
    "独一味": "Lamiophlomis rotata (Benth.) Kudo",
    "狼毒": "Euphorbia fischeriana Steud.",
    "猪牙皂": "Gleditsia sinensis Lam.",
    "猪胆粉": "Sus scrofa domestica Brisson",
    "猫爪草": "Ranunculus ternatus Thunb.",
    "玄明粉": "Natrii Sulfas Exsiccatus",
    "珍珠": "Pteria martensii (Dunker)",
    "珍珠母": "Pteria martensii (Dunker)",
    "珠子参": "Panax japonicus C.A.Mey.",
    "瓜子金": "Polygala japonica Houtt.",
    "瓜蒌子": "Trichosanthes kirilowii Maxim.",
    "瓜蒌皮": "Trichosanthes kirilowii Maxim.",
    "瓦松": "Orostachys fimbriata (Turcz.) Berger",
    "瓦楞子": "Arca subcrenata Lischke",
    "甘松": "Nardostachys jatamansi DC.",
    "甜瓜子": "Cucumis melo L.",
    "白头翁": "Pulsatilla chinensis (Bge.) Regel",
    "白果": "Ginkgo biloba L.",
    "白蔹": "Ampelopsis japonica (Thunb.) Makino",
    "皂矾": "Melanteritum",
    "皂角刺": "Gleditsia sinensis Lam.",
    "瞿麦": "Dianthus superbus L.",
    "石决明": "Haliotis diversicolor Reeve",
    "石吊兰": "Lysionotus pauciflorus Maxim.",
    "石榴皮": "Punica granatum L.",
    "石膏": "Gypsum Fibrosum",
    "石韦": "Pyrrosia lingua (Thunb.) Farwell",
    "硫黄": "Sulfur",
    "禹余粮": "Limonitum",
    "禹州漏芦": "Echinops latifolius Tausch",
    "积雪草": "Centella asiatica (L.) Urb.",
    "稻芽": "Oryza sativa L.",
    "穿山龙": "Dioscorea nipponica Makino",
    "竹节参": "Panax japonicus C.A.Mey.",
    "竹茹": "Bambusa tuldoides Munro",
    "筋骨草": "Ajuga decumbens Thunb.",
    "粉萆薢": "Dioscorea hypoglauca Palib.",
    "粉葛": "Pueraria thomsonii Benth.",
    "紫珠叶": "Callicarpa bodinieri Levl.",
    "紫石英": "Fluoritum",
    "紫花前胡": "Peucedanum decursivum (Miq.) Maxim.",
    "紫苏梗": "Perilla frutescens (L.) Britt.",
    "紫菀": "Aster tataricus L.f.",
    "紫萁贯众": "Osmunda japonica Thunb.",
    "红参": "Panax ginseng C.A.Mey.",
    "红大戟": "Knoxia valerianoides Thorel et Pitard",
    "红粉": "Hydrargyri Oxydum Rubrum",
    "红芪": "Hedysarum polybotrys Hand.-Mazz.",
    "红花龙胆": "Gentiana rhodantha Franch.",
    "红豆蔻": "Alpinia galanga (L.) Willd.",
    "络石藤": "Trachelospermum jasminoides (Lindl.) Lem.",
    "绵萆薢": "Dioscorea spongiosa J.Q.Xi, M.Mizuno et W.L.Zhao",
    "绵马贯众": "Dryopteris crassirhizoma Nakai",
    "绵马贯众炭": "Dryopteris crassirhizoma Nakai",
    "罂粟壳": "Papaver somniferum L.",
    "罗布麻叶": "Apocynum venetum L.",
    "羚羊角": "Saiga tatarica Linnaeus",
    "翻白草": "Potentilla discolor Bge.",
    "翼首草": "Pterocephalus hookeri (C.B.Clarke) Hoeck",
    "老鹳草": "Geranium wilfordii Maxim.",
    "肿节风": "Sarcandra glabra (Thunb.) Nakai",
    "胆南星": "Arisaema erubescens (Wall.) Schott",
    "胖大海": "Sterculia lychnophora Hance",
    "胡椒": "Piper nigrum L.",
    "胡芦巴": "Trigonella foenum-graecum L.",
    "胡黄连": "Picrorhiza scrophulariiflora Pennell",
    "臭灵丹草": "Laggera pterodonta (DC.) Benth.",
    "艾片": "Blumea balsamifera (L.) DC.",
    "芒硝": "Natrii Sulfas",
    "芥子": "Sinapis alba L.",
    "芦荟": "Aloe barbadensis Miller",
    "芫花": "Daphne genkwa Sieb. et Zucc.",
    "花蕊石": "Ophicalcitum",
    "苏合香": "Liquidambar orientalis Mill.",
    "苘麻子": "Abutilon theophrasti Medic.",
    "苦地丁": "Corydalis bungeana Turcz.",
    "苦木": "Picrasma quassioides (D.Don) Benn.",
    "苦楝皮": "Melia azedarach L.",
    "苦玄参": "Picria felterrae Lour.",
    "茜草": "Rubia cordifolia L.",
    "茯苓皮": "Poria cocos (Schw.) Wolf",
    "茺蔚子": "Leonurus japonicus Houtt.",
    "荆芥炭": "Nepeta cataria L.",
    "荆芥穗": "Nepeta cataria L.",
    "荆芥穗炭": "Nepeta cataria L.",
    "草乌叶": "Aconitum kusnezoffii Reichb.",
    "荔枝核": "Litchi chinensis Sonn.",
    "莲房": "Nelumbo nucifera Gaertn.",
    "莲须": "Nelumbo nucifera Gaertn.",
    "菊苣": "Cichorium intybus L.",
    "菥蓂": "Thlaspi arvense L.",
    "萹蓄": "Polygonum aviculare L.",
    "葶苈子": "Lepidium apetalum Willd.",
    "蒺藜": "Tribulus terrestris L.",
    "蓍草": "Achillea alpina L.",
    "蓖麻子": "Ricinus communis L.",
    "蓝布正": "Geum japonicum Thunb.",
    "蓼大青叶": "Polygonum tinctorium Ait.",
    "蕤仁": "Prinsepia uniflora Batal.",
    "蕲蛇": "Bungarus multicinctus Blyth",
    "薤白": "Allium macrostemon Bge.",
    "藏菖蒲": "Acorus calamus L.",
    "藕节": "Nelumbo nucifera Gaertn.",
    "虫白蜡": "Ericerus pela (Chavannes) Guerin",
    "蛇床子": "Cnidium monnieri (L.) Cuss.",
    "蛇蜕": "Zaocys dhumnades (Cantor)",
    "蛤壳": "Cyclina sinensis (Gmelin)",
    "蛤蚧": "Gekko gecko Linnaeus",
    "蜂房": "Polistes mandarinus Saussure",
    "蜂胶": "Apis mellifera Linnaeus",
    "蜂蜜": "Apis mellifera Linnaeus",
    "蜂蜡": "Apis mellifera Linnaeus",
    "蜘蛛香": "Valeriana jatamansi Jones",
    "蟾酥": "Bufo bufo gargarizans Cantor",
    "血余炭": "Crinis Carbonisatus",
    "裸花紫珠": "Callicarpa nudiflora Hook. et Arn.",
    "西河柳": "Tamarix chinensis Lour.",
    "西瓜霜": "Citrullus lanatus (Thunb.) Matsum. et Nakai",
    "西青果": "Terminalia chebula Retz.",
    "覆盆子": "Rubus chingii Hu",
    "诃子": "Terminalia chebula Retz.",
    "谷精草": "Eriocaulon buergerianum Koern.",
    "谷芽": "Setaria italica (L.) Beauv.",
    "豨莶草": "Siegesbeckia orientalis L.",
    "贯叶金丝桃": "Hypericum perforatum L.",
    "赤石脂": "Halloysitum Rubrum",
    "赭石": "Haematitum",
    "轻粉": "Calomelas",
    "辣椒": "Capsicum annuum L.",
    "连钱草": "Glechoma longituba (Nakai) Kupr.",
    "通关藤": "Marsdenia tenacissima (Roxb.) Wight et Arn.",
    "通草": "Tetrapanax papyrifer (Hook.) K.Koch",
    "重楼": "Paris polyphylla Smith",
    "野木瓜": "Stauntonia chinensis DC.",
    "野马追": "Eupatorium lindleyanum DC.",
    "金果榄": "Tinospora sagittata (Oliv.) Gagnep.",
    "金沸草": "Inula japonica Thunb.",
    "金礞石": "Lapis Micae seu Chloriti",
    "金钱白花蛇": "Bungarus multicinctus Blyth",
    "金铁锁": "Psammosilene tunicoides W.C.Wu et C.Y.Wu",
    "金龙胆草": "Conyza blinii Levl.",
    "钟乳石": "Stalactitum",
    "铁皮石斛": "Dendrobium officinale Kimura et Migo",
    "银杏叶": "Ginkgo biloba L.",
    "银柴胡": "Stellaria dichotoma L.",
    "锁阳": "Cynomorium songaricum Rupr.",
    "锦灯笼": "Physalis alkekengi L.",
    "闹羊花": "Rhododendron molle (Blume) G.Don",
    "阿胶": "Equus asinus Linnaeus",
    "阿魏": "Ferula assafoetida L.",
    "雄黄": "Realgar",
    "雷丸": "Omphalia lapidescens Schroet.",
    "青叶胆": "Swertia mileensis T.N.Ho et W.L.Shi",
    "青果": "Canarium album (Lour.) Raeusch.",
    "青礞石": "Lapis Chloriti",
    "青葙子": "Celosia argentea L.",
    "青风藤": "Sinomenium acutum (Thunb.) Rehd. et Wils.",
    "韭菜子": "Allium tuberosum Rottler ex Spreng.",
    "颠茄草": "Atropa belladonna L.",
    "首乌藤": "Fallopia multiflora (Thunb.) Harald.",
    "香加皮": "Periploca sepium Bge.",
    "香橼": "Citrus medica L.",
    "香薷": "Mosla chinensis Maxim.",
    "马勃": "Lasiosphaera fenzlii Reich.",
    "马钱子粉": "Strychnos nux-vomica L.",
    "马鞭草": "Verbena officinalis L.",
    "高山辣根菜": "Pegaeophyton scapiflorum (Hook.f. et Thoms.) Marq. et Shaw",
    "鳖甲": "Trionyx sinensis Wiegmann",
    "鸡血藤": "Spatholobus suberectus Dunn",
    "鸡骨草": "Abrus cantoniensis Hance",
    "鸭跖草": "Commelina communis L.",
    "鹅不食草": "Centipeda minima (L.) A.Br. et Aschers.",
    "鹤虱": "Carpesium abrotanoides L.",
    "鹿衔草": "Pyrola calliantha H.Andr.",
    "鹿角": "Cervus nippon Temminck",
    "鹿角胶": "Cervus nippon Temminck",
    "鹿角霜": "Cervus nippon Temminck",
    "麝香": "Moschus berezovskii Flerov",
    "麦芽": "Hordeum vulgare L.",
    "麻黄根": "Ephedra sinica Stapf",
    "黄山药": "Dioscorea panthaica Prain et Burkill",
    "黄藤": "Fibraurea recisa Pierre",
    "黄蜀葵花": "Abelmoschus manihot (L.) Medic.",
    "黑种草子": "Nigella glandulifera Freyn et Sint.",
    "黑芝麻": "Sesamum indicum L.",
    "黑豆": "Glycine max (L.) Merr.",
    "龙脷叶": "Sauropus spatulifolius Beille",
    "龟甲胶": "Chinemys reevesii (Gray)",
}

def enrich_v3():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    updated = 0
    for cn, latin in LATIN_MAP.items():
        result = c.execute(
            "UPDATE tcm_single_herb SET name_latin=?, data_level='aligned' WHERE name_cn=? AND (name_latin IS NULL OR name_latin='')",
            (latin, cn)
        )
        if result.rowcount > 0:
            updated += result.rowcount

    conn.commit()
    total = c.execute("SELECT COUNT(*) FROM tcm_single_herb").fetchone()[0]
    aligned = c.execute("SELECT COUNT(*) FROM tcm_single_herb WHERE name_latin IS NOT NULL AND name_latin != ''").fetchone()[0]
    print(f"总药材: {total}")
    print(f"已填充拉丁名: {aligned} ({aligned*100//total}%)")
    print(f"本次更新: {updated} 条")
    conn.close()

    if SUPABASE_URL and SUPABASE_KEY:
        from supabase import create_client
        client = create_client(SUPABASE_URL, SUPABASE_KEY)
        data = [{"name_cn": cn, "name_latin": latin, "data_level": "aligned"}
                for cn, latin in LATIN_MAP.items()]
        for i in range(0, len(data), 50):
            client.table("tcm_single_herb").upsert(
                data[i:i+50], on_conflict="name_cn").execute()
        print(f"Supabase同步完成: {len(data)} 条")

if __name__ == "__main__":
    enrich_v3()
